// Supported UI languages. zh/en strings live in app.js; the other four load an
// on-demand pack from js/i18n/<code>.js. `html` doubles as the hreflang value,
// `cnFirst` decides whether the China column comes first (only for zh).
window.LANGS = [
  { code: 'zh', label: '中文',    html: 'zh-CN', locale: 'zh_CN', cnFirst: true },
  { code: 'en', label: 'English', html: 'en',    locale: 'en_US', cnFirst: false },
  { code: 'ja', label: '日本語',  html: 'ja',    locale: 'ja_JP', cnFirst: false },
  { code: 'ko', label: '한국어',  html: 'ko',    locale: 'ko_KR', cnFirst: false },
  { code: 'es', label: 'Español', html: 'es',    locale: 'es_ES', cnFirst: false },
  { code: 'ru', label: 'Русский', html: 'ru',    locale: 'ru_RU', cnFirst: false }
];

// Navigation data. Each item: name / url / intro (zh+en) / tag
window.CHINA_SITES = [
  { name: 'DeepSeek', url: 'https://chat.deepseek.com', tag: 'assistant', intro: { zh: '深度求索出品的推理与对话大模型', en: 'Reasoning & chat model by DeepSeek' } },
  { name: '豆包', url: 'https://www.doubao.com', tag: 'assistant', intro: { zh: '字节跳动智能助手，语音与图像能力强', en: 'ByteDance AI assistant with voice & vision' } },
  { name: 'Kimi', url: 'https://kimi.moonshot.cn', tag: 'assistant', intro: { zh: '月之暗面，超长上下文智能助手', en: 'Moonshot AI, ultra-long context assistant' } },
  { name: '通义千问', url: 'https://tongyi.aliyun.com/qianwen', tag: 'assistant', intro: { zh: '阿里巴巴大模型助手，生态完善', en: 'Alibaba LLM assistant with rich ecosystem' } },
  { name: '智谱清言', url: 'https://chatglm.cn', tag: 'assistant', intro: { zh: '智谱 AI 出品，GLM 系列模型对话入口', en: 'Chat entry for Zhipu AI GLM models' } },
  { name: '腾讯元宝', url: 'https://yuanbao.tencent.com', tag: 'assistant', intro: { zh: '腾讯混元大模型助手，深度整合微信内容', en: 'Tencent Hunyuan assistant, WeChat content integrated' } },
  { name: '文心一言', url: 'https://yiyan.baidu.com', tag: 'assistant', intro: { zh: '百度文心大模型，中文知识问答见长', en: 'Baidu ERNIE Bot, strong in Chinese Q&A' } },
  { name: '讯飞星火', url: 'https://xinghuo.xfyun.cn', tag: 'assistant', intro: { zh: '科大讯飞星火大模型，语音识别领先', en: 'iFlytek Spark, leading speech tech' } },
  { name: '海螺AI', url: 'https://hailuoai.com', tag: 'video', intro: { zh: 'MiniMax 出品，视频与对话生成', en: 'MiniMax video & chat generation' } },
  { name: '即梦AI', url: 'https://jimeng.jianying.com', tag: 'image', intro: { zh: '剪映团队的一站式 AI 图像视频创作', en: 'One-stop AI image & video creation' } },
  { name: '可灵AI', url: 'https://klingai.kuaishou.com', tag: 'video', intro: { zh: '快手出品，高质量 AI 视频生成', en: 'Kuaishou high-quality AI video generation' } },
  { name: '秘塔AI搜索', url: 'https://metaso.cn', tag: 'search', intro: { zh: '无广告、结构化的 AI 搜索引擎', en: 'Ad-free, structured AI search engine' } },
  { name: '纳米AI', url: 'https://www.n.cn', tag: 'search', intro: { zh: '360 出品，多模型聚合 AI 搜索', en: '360 multi-model AI search' } },
  { name: '扣子', url: 'https://www.coze.cn', tag: 'agent', intro: { zh: '字节跳动 AI Agent 无代码搭建平台', en: 'ByteDance no-code AI agent builder' } },
  { name: 'DeepSeek Harness', url: 'https://www.deepseek.com/harness', tag: 'agent', intro: { zh: 'DeepSeek 官方智能体运行框架，桌面端多模式执行任务', en: 'DeepSeek official agent runtime framework with desktop app' } },
  { name: '文心智能体', url: 'https://agents.baidu.com', tag: 'agent', intro: { zh: '百度智能体创建与分发平台', en: 'Baidu agent creation & distribution platform' } },
  { name: '星辰Agent', url: 'https://agent.xfyun.cn', tag: 'agent', intro: { zh: '科大讯飞智能体开发平台', en: 'iFlytek agent development platform' } },
  { name: 'WorkBuddy', url: 'https://www.workbuddy.cn', tag: 'agent', intro: { zh: '腾讯云出品，自主拆解执行任务的职场 AI Agent', en: 'Tencent Cloud autonomous work agent' } },
  { name: 'Qoder', url: 'https://qoder.com', tag: 'agent', intro: { zh: '阿里巴巴智能体编程工作台，从编码扩展到日常任务', en: 'Alibaba agentic coding workbench' } },
  { name: 'Trae', url: 'https://www.trae.cn', tag: 'coding', intro: { zh: '字节跳动 AI 原生 IDE，国内版免费', en: 'ByteDance AI-native IDE' } },
  { name: 'CodeBuddy', url: 'https://www.codebuddy.cn', tag: 'coding', intro: { zh: '腾讯云 AI 编程助手与工艺级代码智能体', en: 'Tencent Cloud AI coding assistant & agent' } },
  { name: '通义灵码', url: 'https://lingma.aliyun.com', tag: 'coding', intro: { zh: '阿里云智能编码助手，插件生态广', en: 'Alibaba Cloud intelligent coding assistant' } },
  { name: 'Vidu', url: 'https://www.vidu.cn', tag: 'video', intro: { zh: '生数科技视频大模型，主体一致性见长', en: 'Shengshu video model with strong subject consistency' } },
  { name: 'LiblibAI', url: 'https://www.liblib.art', tag: 'image', intro: { zh: 'AI 图像创作社区与模型分享平台', en: 'AI image creation community & model hub' } },
  { name: '跃问', url: 'https://yuewen.stepfun.com', tag: 'assistant', intro: { zh: '阶跃星辰多模态助手，视觉理解强', en: 'StepFun multimodal assistant with strong vision' } },
  { name: '天工AI', url: 'https://www.tiangong.cn', tag: 'search', intro: { zh: '昆仑万维 AI 搜索与音乐生成', en: 'Kunlun AI search & music generation' } },
  { name: 'WPS AI', url: 'https://ai.wps.cn', tag: 'productivity', intro: { zh: '金山办公套件内置 AI，写文档做表格', en: 'AI built into the WPS office suite' } },
  { name: '灵光', url: 'https://www.lingguang.com', tag: 'assistant', intro: { zh: '蚂蚁集团生活创意 AI 应用', en: 'Ant Group lifestyle & creativity AI app' } },
  { name: '网易天音', url: 'https://tianyin.music.163.com', tag: 'audio', intro: { zh: '网易一站式 AI 音乐创作平台', en: 'NetEase one-stop AI music creation' } },
  { name: 'AI工具集', url: 'https://ai-bot.cn', tag: 'portal', intro: { zh: '国内 AI 产品与工具大全导航', en: 'Huge directory of Chinese AI tools' } },
  { name: '机器之心', url: 'https://www.jiqizhixin.com', tag: 'media', intro: { zh: '专业的 AI 科技媒体与学术社区', en: 'Professional AI tech media & community' } },
  { name: '量子位', url: 'https://www.qbitai.com', tag: 'media', intro: { zh: '关注 AI 产业与前沿科技的媒体', en: 'AI industry and frontier tech news' } },
];

window.US_SITES = [
  { name: 'ChatGPT', url: 'https://chatgpt.com', tag: 'assistant', intro: { zh: 'OpenAI 旗舰对话助手，生态最完善', en: 'OpenAI flagship assistant with the biggest ecosystem' } },
  { name: 'Claude', url: 'https://claude.ai', tag: 'assistant', intro: { zh: 'Anthropic 出品，长文本与编程见长', en: 'Anthropic model, strong writing & coding' } },
  { name: 'Gemini', url: 'https://gemini.google.com', tag: 'assistant', intro: { zh: '谷歌多模态大模型，深度整合 Google 全家桶', en: 'Google multimodal model, Google-suite integrated' } },
  { name: 'Perplexity', url: 'https://www.perplexity.ai', tag: 'search', intro: { zh: '带引用来源的 AI 答案引擎', en: 'AI answer engine with citations' } },
  { name: 'Microsoft Copilot', url: 'https://copilot.microsoft.com', tag: 'assistant', intro: { zh: '微软 AI 助手，打通 Office 与 Bing', en: 'Microsoft AI assistant across Office & Bing' } },
  { name: 'Grok', url: 'https://grok.com', tag: 'assistant', intro: { zh: 'xAI 出品，接入 X 平台实时数据', en: 'xAI assistant with live X data' } },
  { name: 'Midjourney', url: 'https://www.midjourney.com', tag: 'image', intro: { zh: '艺术风格标杆的 AI 图像生成', en: 'Benchmark for artistic AI image generation' } },
  { name: 'Poe', url: 'https://poe.com', tag: 'portal', intro: { zh: '一个订阅同时使用多家大模型', en: 'Multi-model chat hub in one app' } },
  { name: 'LMArena', url: 'https://lmarena.ai', tag: 'portal', intro: { zh: '众包盲测的大模型排行榜', en: 'Crowd-sourced blind-test LLM leaderboard' } },
  { name: 'Hugging Face', url: 'https://huggingface.co', tag: 'portal', intro: { zh: '全球最大开源模型与数据集社区', en: 'World\'s largest open model & dataset hub' } },
  { name: 'OpenAI', url: 'https://openai.com', tag: 'lab', intro: { zh: 'GPT 系列模型的研发机构官网', en: 'Official site of the GPT series lab' } },
  { name: 'Anthropic', url: 'https://www.anthropic.com', tag: 'lab', intro: { zh: 'Claude 背后的安全 AI 实验室', en: 'Safety-first AI lab behind Claude' } },
  { name: 'Google DeepMind', url: 'https://deepmind.google', tag: 'lab', intro: { zh: 'Gemini 与 AlphaFold 的研究院', en: 'Lab behind Gemini and AlphaFold' } },
  { name: 'Cursor', url: 'https://cursor.com', tag: 'coding', intro: { zh: 'AI 优先的代码编辑器，编程爆款', en: 'The AI-first code editor' } },
  { name: 'Manus', url: 'https://manus.im', tag: 'agent', intro: { zh: '自主执行任务的通用 AI Agent', en: 'Autonomous general-purpose AI agent' } },
  { name: 'Codex', url: 'https://chatgpt.com/codex', tag: 'agent', intro: { zh: 'OpenAI 云端编程智能体，可并行处理多个工程任务', en: 'OpenAI cloud coding agent for parallel engineering tasks' } },
  { name: 'Claude Code', url: 'https://claude.com/claude-code', tag: 'coding', intro: { zh: 'Anthropic 终端编程智能体，工程能力标杆', en: 'Anthropic terminal coding agent, engineering benchmark' } },
  { name: 'Windsurf', url: 'https://windsurf.com', tag: 'coding', intro: { zh: 'Cascade 智能体驱动的 AI IDE', en: 'AI IDE powered by the Cascade agent' } },
  { name: 'Replit', url: 'https://replit.com', tag: 'coding', intro: { zh: '浏览器里用 Agent 从零造应用', en: 'Build apps from scratch with an in-browser agent' } },
  { name: 'v0', url: 'https://v0.dev', tag: 'coding', intro: { zh: 'Vercel 出品，一句话生成 UI 前端', en: 'Vercel tool that generates UI from a prompt' } },
  { name: 'Sora', url: 'https://sora.com', tag: 'video', intro: { zh: 'OpenAI 视频生成与社交化创作社区', en: 'OpenAI video generation & remix community' } },
  { name: 'NotebookLM', url: 'https://notebooklm.google.com', tag: 'assistant', intro: { zh: '谷歌资料研读助手，播客式摘要出圈', en: 'Google research assistant famous for podcast summaries' } },
  { name: 'Suno', url: 'https://suno.com', tag: 'audio', intro: { zh: '文本生成完整歌曲的爆款音乐模型', en: 'Hit text-to-song music model' } },
  { name: 'Ideogram', url: 'https://ideogram.ai', tag: 'image', intro: { zh: '文字渲染最强的 AI 生图工具之一', en: 'Top AI image tool for in-image text' } },
  { name: 'Gamma', url: 'https://gamma.app', tag: 'productivity', intro: { zh: 'AI 一键生成幻灯片与文档', en: 'AI-generated slides & docs in one click' } },
  { name: 'Character.AI', url: 'https://character.ai', tag: 'assistant', intro: { zh: '角色扮演对话社区，陪伴类头部产品', en: 'Leading roleplay & companion chat community' } },
  { name: 'Genspark', url: 'https://www.genspark.ai', tag: 'agent', intro: { zh: '超级 Agent，自动生成网页与幻灯片', en: 'Super agent that builds pages & slides' } },
  { name: 'Devin', url: 'https://devin.ai', tag: 'agent', intro: { zh: 'Cognition 出品的 AI 软件工程师', en: 'AI software engineer by Cognition' } },
  { name: 'Lindy', url: 'https://www.lindy.ai', tag: 'agent', intro: { zh: '无代码 AI 工作流 Agent 平台', en: 'No-code AI agent workflow platform' } },
  { name: 'Browser Use', url: 'https://browser-use.com', tag: 'agent', intro: { zh: '让 AI 直接操作浏览器的开源 Agent', en: 'Open-source agent that operates the browser' } },
  { name: 'Runway', url: 'https://runwayml.com', tag: 'video', intro: { zh: 'Gen 系列视频生成，影视级工具', en: 'Gen-series video models for creators' } },
  { name: 'ElevenLabs', url: 'https://elevenlabs.io', tag: 'audio', intro: { zh: '高保真 AI 语音合成与配音', en: 'High-fidelity AI voice synthesis' } },
];

// 开源 AI 项目：仅收录普通用户在生活/商业中可直接使用的工具类项目，
// 不含模型权重、深度学习/推理/微调框架等面向高级开发者的条目。
window.OSS_PROJECTS = [
  { name: 'Open WebUI', url: 'https://github.com/open-webui/open-webui', tag: 'assistant', intro: { zh: '自托管的友好 AI 聊天界面，可接本地或云端模型', en: 'Self-hosted, user-friendly AI chat UI for local or cloud models' } },
  { name: 'LobeChat', url: 'https://github.com/lobehub/lobe-chat', tag: 'assistant', intro: { zh: '现代化开源 AI 聊天与助手界面，插件丰富', en: 'Modern open-source AI chat & assistant UI with plugins' } },
  { name: 'LibreChat', url: 'https://github.com/LibreChat-AI/LibreChat', tag: 'assistant', intro: { zh: '自托管多模型聊天平台，支持 Agent 与插件', en: 'Self-hosted multi-model chat with agents & plugins' } },
  { name: 'Jan', url: 'https://github.com/janhq/jan', tag: 'assistant', intro: { zh: '100% 离线运行的桌面版 ChatGPT 替代品', en: 'Offline desktop alternative to ChatGPT, runs 100% locally' } },
  { name: 'Vane', url: 'https://github.com/ItzCrazyKns/Vane', tag: 'search', intro: { zh: '开源 AI 搜索/问答引擎（原 Perplexica）', en: 'Open-source AI search & answer engine (formerly Perplexica)' } },
  { name: 'GPT-Researcher', url: 'https://github.com/assafelovic/gpt-researcher', tag: 'agent', intro: { zh: '自主深度研究智能体，自动生成带引用的研究报告', en: 'Autonomous agent that produces cited, in-depth research reports' } },
  { name: 'Dify', url: 'https://github.com/langgenius/dify', tag: 'agent', intro: { zh: '可视化搭建 AI 应用与智能体的低代码平台', en: 'Low-code platform to build AI apps & agents visually' } },
  { name: 'Flowise', url: 'https://github.com/FlowiseAI/Flowise', tag: 'agent', intro: { zh: '拖拽式搭建 LLM 应用与智能体工作流', en: 'Drag-and-drop builder for LLM apps & agent workflows' } },
  { name: 'n8n', url: 'https://github.com/n8n-io/n8n', tag: 'agent', intro: { zh: '带原生 AI 能力的工作流自动化平台', en: 'Workflow automation platform with native AI capabilities' } },
  { name: 'Activepieces', url: 'https://github.com/activepieces/activepieces', tag: 'agent', intro: { zh: '无代码 AI 自动化与智能体搭建平台', en: 'No-code AI automation & agent building platform' } },
  { name: 'ComfyUI', url: 'https://github.com/comfyanonymous/ComfyUI', tag: 'image', intro: { zh: '节点式 AI 图像/视频创作工作流，创作者常用', en: 'Node-based AI image/video workflow, popular with creators' } },
  { name: 'Fooocus', url: 'https://github.com/lllyasviel/Fooocus', tag: 'image', intro: { zh: '极简高质量 AI 绘画，专注提示词即可出图', en: 'Minimal, high-quality AI image generation from prompts' } },
  { name: 'InvokeAI', url: 'https://github.com/invoke-ai/InvokeAI', tag: 'image', intro: { zh: '面向创作者的 Stable Diffusion 创意工作台', en: 'Leading Stable Diffusion creative engine for creators' } },
  { name: 'SD WebUI (A1111)', url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui', tag: 'image', intro: { zh: 'Stable Diffusion 图形界面，AI 绘画易上手', en: 'Web UI for Stable Diffusion, easy AI art for non-coders' } },
  { name: 'MoneyPrinterTurbo', url: 'https://github.com/harry0703/MoneyPrinterTurbo', tag: 'video', intro: { zh: '输入主题一键生成短视频，自媒体/商用利器', en: 'Turn a topic into short videos in one click for creators & business' } },
  { name: 'GPT-SoVITS', url: 'https://github.com/RVC-Boss/GPT-SoVITS', tag: 'audio', intro: { zh: '少样本语音克隆与文本转语音，1 分钟音频即可', en: 'Few-shot voice cloning & TTS from as little as 1 minute of audio' } },
  { name: 'Buzz', url: 'https://github.com/chidiwilliams/buzz', tag: 'audio', intro: { zh: '离线音视频转写与翻译的图形界面（基于 Whisper）', en: 'Offline audio transcription & translation GUI (Whisper-based)' } },
  { name: 'AnythingLLM', url: 'https://github.com/Mintplex-Labs/anything-llm', tag: 'productivity', intro: { zh: '桌面端与你的文档对话，搭建私有知识库', en: 'Desktop app to chat with your docs & build a private knowledge base' } },
  { name: 'FastGPT', url: 'https://github.com/labring/FastGPT', tag: 'productivity', intro: { zh: '开箱即用的知识库问答与智能体平台', en: 'Ready-to-use knowledge-base Q&A & agent platform' } },
  { name: 'RAGFlow', url: 'https://github.com/infiniflow/ragflow', tag: 'productivity', intro: { zh: '深度文档理解的开源知识库问答引擎', en: 'Open-source knowledge-base Q&A with deep doc understanding' } },
  { name: 'Khoj', url: 'https://github.com/khoj-ai/khoj', tag: 'productivity', intro: { zh: '自托管的 AI 第二大脑，检索网页与你的文档作答', en: 'Self-hostable AI second brain answering from the web & your docs' } },
  { name: 'NextAI Translator', url: 'https://github.com/nextai-translator/nextai-translator', tag: 'productivity', intro: { zh: '基于大模型的划词/截图/文档翻译（原 openai-translator）', en: 'LLM-powered text/screenshot/doc translation (formerly openai-translator)' } },
  { name: 'Umi-OCR', url: 'https://github.com/hiroi-sora/Umi-OCR', tag: 'productivity', intro: { zh: '免费离线 OCR，截图/批量文字识别与整理', en: 'Free offline OCR for screenshot & batch text recognition' } },
  { name: 'Ollama', url: 'https://github.com/ollama/ollama', tag: 'app', intro: { zh: '一条命令在本地跑大模型，隐私离线可用', en: 'Run LLMs locally in one command, private & offline' } },
];

// AI Agent Skills：给大模型/智能体扩展能力的技能包（含 SKILL.md）。
// 收录 skills.sh 社区高安装量技能与 Anthropic 官方技能，按热度排序。
window.SKILLS = [
  { name: 'find-skills', url: 'https://skills.sh/vercel-labs/skills/find-skills', tag: 'skill-tool', intro: { zh: '社区最热门：发现并一键安装各类 Agent 技能（360 万+ 安装）', en: 'Most popular: discover & install agent skills in one step (3.6M+ installs)' } },
  { name: 'grill-me', url: 'https://skills.sh/mattpocock/skills/grill-me', tag: 'skill-plan', intro: { zh: '连环追问，系统性压力测试你的方案与设计（120 万+ 安装）', en: 'Relentless questioning that stress-tests your plans & designs (1.2M+ installs)' } },
  { name: 'agent-browser', url: 'https://skills.sh/vercel-labs/agent-browser/agent-browser', tag: 'skill-tool', intro: { zh: '让 Agent 操控浏览器：导航、填表、点击、抓取数据', en: 'Browser automation for agents: navigate, fill forms, click & extract data' } },
  { name: 'frontend-design', url: 'https://skills.sh/anthropics/skills/frontend-design', tag: 'skill-dev', intro: { zh: 'Anthropic 官方：生成有设计感的生产级前端界面', en: 'By Anthropic: distinctive, production-grade frontend interfaces' } },
  { name: 'teach', url: 'https://skills.sh/mattpocock/skills/teach', tag: 'skill-learn', intro: { zh: '用任务与互动课程带你深入学习一个主题', en: 'Guides deep learning of a topic via missions & interactive lessons' } },
  { name: 'domain-modeling', url: 'https://skills.sh/mattpocock/skills/domain-modeling', tag: 'skill-plan', intro: { zh: '打磨项目领域模型：挑战术语、构造边界用例、记录决策', en: 'Sharpens your domain model: challenges terms, invents edge cases, records decisions' } },
  { name: 'video-edit', url: 'https://skills.sh/genmedia-labs/skills/video-edit', tag: 'skill-content', intro: { zh: '把剪辑意图智能路由到合适的 RunComfy 模型（改风格/运动/换装）', en: 'Routes video-edit intents to the right RunComfy model (restyle/motion/outfit swap)' } },
  { name: 'hyperframes', url: 'https://skills.sh/heygen-com/hyperframes/hyperframes', tag: 'skill-content', intro: { zh: 'HeyGen 出品：用 HTML/代码渲染动画与字幕视频', en: 'By HeyGen: HTML/code-based video composition rendering animations & captions' } },
  { name: 'reddit-automation', url: 'https://skills.sh/flowkit-labs/skills/reddit-automation', tag: 'skill-market', intro: { zh: '发现需要你产品的 Reddit 帖子并起草坦诚的推广回复', en: 'Finds Reddit threads needing your product & drafts honest, disclosed replies' } },
  { name: 'skill-creator', url: 'https://skills.sh/anthropics/skills/skill-creator', tag: 'skill-dev', intro: { zh: 'Anthropic 官方：创建并测试你自己的自定义技能', en: 'By Anthropic: build & test your own custom skills' } },
  { name: 'pdf', url: 'https://skills.sh/anthropics/skills/pdf', tag: 'skill-doc', intro: { zh: 'Anthropic 官方：PDF 提取/合并/拆分/OCR/表单填写', en: 'By Anthropic: PDF extraction, merge/split, OCR & form filling' } },
  { name: 'docx', url: 'https://skills.sh/anthropics/skills/docx', tag: 'skill-doc', intro: { zh: 'Anthropic 官方：生成与编辑 Word 文档', en: 'By Anthropic: create & edit Word documents' } },
  { name: 'xlsx', url: 'https://skills.sh/anthropics/skills/xlsx', tag: 'skill-doc', intro: { zh: 'Anthropic 官方：生成与处理 Excel 电子表格', en: 'By Anthropic: create & process Excel spreadsheets' } },
  { name: 'canvas-design', url: 'https://skills.sh/anthropics/skills/canvas-design', tag: 'skill-content', intro: { zh: 'Anthropic 官方：海报与画布类视觉设计', en: 'By Anthropic: poster & canvas-style visual design' } },
];

// Model leaderboards, one board per modality. Regenerate with:
//   node scripts/update-ranking.mjs   (see scripts/update-ranking.mjs header)
window.RANK_BOARDS = [
  {
    key: 'text',
    label: { zh: '文本对话', en: 'Text Chat' },
    asOf: '2026-09',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'Gemini 4 Argon (high)', org: 'Google', score: 1533 },
        { r: 2, name: 'Claude Opus 5.5 (high)', org: 'Anthropic', score: 1512 },
        { r: 3, name: 'Claude Fable 5.1 Max', org: 'Anthropic', score: 1511 },
        { r: 4, name: 'Claude Opus 5 Max', org: 'Anthropic', score: 1507 },
        { r: 5, name: 'Claude Opus 4.6 (high)', org: 'Anthropic', score: 1504 },
        { r: 6, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 1503 },
        { r: 7, name: 'Claude Opus 4.6', org: 'Anthropic', score: 1498 },
        { r: 8, name: 'Gemini 3.8 Flash (high)', org: 'Google', score: 1496 },
        { r: 9, name: 'Claude Fable 5 (high)', org: 'Anthropic', score: 1492 },
        { r: 10, name: 'MiMo V2.6 Pro', org: 'Xiaomi', score: 1491 },
        { r: 11, name: 'Claude Opus 4.7 (high)', org: 'Anthropic', score: 1490 },
        { r: 12, name: 'Muse Spark 1.3 Max', org: 'Meta', score: 1490 },
        { r: 13, name: 'Gemini 3.7 Flash (high)', org: 'Google', score: 1487 },
        { r: 14, name: 'Muse Spark 1.2 (xhigh)', org: 'Meta', score: 1484 },
        { r: 15, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1484 },
        { r: 16, name: 'Gemini 3.5 Flash (high)', org: 'Google', score: 1481 },
        { r: 17, name: 'Qwen3.8 Max', org: 'Alibaba', score: 1481 },
        { r: 18, name: 'Gemini 3.1 Pro Preview', org: 'Google', score: 1480 },
        { r: 19, name: 'Muse Spark 1.1', org: 'Meta', score: 1480 },
        { r: 20, name: 'Gemini 3.6 Flash (high)', org: 'Google', score: 1480 },
        { r: 21, name: 'Gemini 3 Pro', org: 'Google', score: 1479 },
        { r: 22, name: 'Gemini 3.5 Flash (medium)', org: 'Google', score: 1478 },
        { r: 23, name: 'Kimi K3 Max', org: 'Moonshot AI', score: 1476 },
        { r: 24, name: 'Qwen3.7 Max Preview', org: 'Alibaba', score: 1475 },
        { r: 25, name: 'Muse Spark', org: 'Meta', score: 1474 },
        { r: 26, name: 'GLM 5.3 Max', org: 'Zhipu AI', score: 1472 },
        { r: 27, name: 'GPT 5.5 (high)', org: 'OpenAI', score: 1471 },
        { r: 28, name: 'Qwen3.5 Max Preview', org: 'Alibaba', score: 1471 },
        { r: 29, name: 'GLM 5.3 Flash', org: 'Zhipu AI', score: 1470 },
        { r: 30, name: 'GLM 5.2 Max', org: 'Zhipu AI', score: 1470 }
      ],
      cn: [
        { r: 1, name: 'MiMo V2.6 Pro', org: 'Xiaomi', score: 1491 },
        { r: 2, name: 'Qwen3.8 Max', org: 'Alibaba', score: 1481 },
        { r: 3, name: 'Kimi K3 Max', org: 'Moonshot AI', score: 1476 },
        { r: 4, name: 'Qwen3.7 Max Preview', org: 'Alibaba', score: 1475 },
        { r: 5, name: 'GLM 5.3 Max', org: 'Zhipu AI', score: 1472 },
        { r: 6, name: 'Qwen3.5 Max Preview', org: 'Alibaba', score: 1471 },
        { r: 7, name: 'GLM 5.3 Flash', org: 'Zhipu AI', score: 1470 },
        { r: 8, name: 'GLM 5.2 Max', org: 'Zhipu AI', score: 1470 },
        { r: 9, name: 'ERNIE 5.1', org: 'Baidu', score: 1468 },
        { r: 10, name: 'MiMo V2.5 Pro', org: 'Xiaomi', score: 1465 },
        { r: 11, name: 'GLM 5.1', org: 'Zhipu AI', score: 1461 },
        { r: 12, name: 'DeepSeek V4.1 Flash Max', org: 'DeepSeek', score: 1461 },
        { r: 13, name: 'MiMo V2.6 Flash', org: 'Xiaomi', score: 1458 },
        { r: 14, name: 'Kimi K2.6', org: 'Moonshot AI', score: 1455 },
        { r: 15, name: 'Qwen3.7 Plus', org: 'Alibaba', score: 1455 },
        { r: 16, name: 'DeepSeek V4 Pro', org: 'DeepSeek', score: 1451 },
        { r: 17, name: 'Dola Seed 2.0 Pro', org: 'ByteDance', score: 1449 },
        { r: 18, name: 'Qwen3.6 Max Preview', org: 'Alibaba', score: 1447 },
        { r: 19, name: 'GLM 5', org: 'Zhipu AI', score: 1446 },
        { r: 20, name: 'Kimi K2.5 Thinking', org: 'Moonshot AI', score: 1445 }
      ],
      us: [
        { r: 1, name: 'Gemini 4 Argon (high)', org: 'Google', score: 1533 },
        { r: 2, name: 'Claude Opus 5.5 (high)', org: 'Anthropic', score: 1512 },
        { r: 3, name: 'Claude Fable 5.1 Max', org: 'Anthropic', score: 1511 },
        { r: 4, name: 'Claude Opus 5 Max', org: 'Anthropic', score: 1507 },
        { r: 5, name: 'Claude Opus 4.6 (high)', org: 'Anthropic', score: 1504 },
        { r: 6, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 1503 },
        { r: 7, name: 'Claude Opus 4.6', org: 'Anthropic', score: 1498 },
        { r: 8, name: 'Gemini 3.8 Flash (high)', org: 'Google', score: 1496 },
        { r: 9, name: 'Claude Fable 5 (high)', org: 'Anthropic', score: 1492 },
        { r: 10, name: 'Claude Opus 4.7 (high)', org: 'Anthropic', score: 1490 },
        { r: 11, name: 'Muse Spark 1.3 Max', org: 'Meta', score: 1490 },
        { r: 12, name: 'Gemini 3.7 Flash (high)', org: 'Google', score: 1487 },
        { r: 13, name: 'Muse Spark 1.2 (xhigh)', org: 'Meta', score: 1484 },
        { r: 14, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1484 },
        { r: 15, name: 'Gemini 3.5 Flash (high)', org: 'Google', score: 1481 },
        { r: 16, name: 'Gemini 3.1 Pro Preview', org: 'Google', score: 1480 },
        { r: 17, name: 'Muse Spark 1.1', org: 'Meta', score: 1480 },
        { r: 18, name: 'Gemini 3.6 Flash (high)', org: 'Google', score: 1480 },
        { r: 19, name: 'Gemini 3 Pro', org: 'Google', score: 1479 },
        { r: 20, name: 'Gemini 3.5 Flash (medium)', org: 'Google', score: 1478 }
      ]
    }
  },
  {
    key: 'vision',
    label: { zh: '多模态理解', en: 'Vision' },
    asOf: '2026-09',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'Claude Fable 5 (high)', org: 'Anthropic', score: 1326 },
        { r: 2, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 1321 },
        { r: 3, name: 'Claude Fable 5.1 Max', org: 'Anthropic', score: 1319 },
        { r: 4, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1317 },
        { r: 5, name: 'Claude Opus 4.6 (high)', org: 'Anthropic', score: 1316 },
        { r: 6, name: 'Qwen3.8 Max', org: 'Alibaba', score: 1314 },
        { r: 7, name: 'Gemini 3.7 Flash (high)', org: 'Google', score: 1314 },
        { r: 8, name: 'Claude Opus 4.7 (high)', org: 'Anthropic', score: 1314 },
        { r: 9, name: 'Claude Opus 4.6', org: 'Anthropic', score: 1313 },
        { r: 10, name: 'Gemini 3.8 Flash (high)', org: 'Google', score: 1312 },
        { r: 11, name: 'Gemini 3.5 Flash (high)', org: 'Google', score: 1310 },
        { r: 12, name: 'Muse Spark 1.3 Max', org: 'Meta', score: 1310 },
        { r: 13, name: 'Gemini 3.5 Flash (medium)', org: 'Google', score: 1308 },
        { r: 14, name: 'Muse Spark', org: 'Meta', score: 1306 },
        { r: 15, name: 'Gemini 3 Pro', org: 'Google', score: 1305 },
        { r: 16, name: 'Muse Spark 1.2 (xhigh)', org: 'Meta', score: 1304 },
        { r: 17, name: 'GLM 5.3 Flash', org: 'Zhipu AI', score: 1304 },
        { r: 18, name: 'GPT 5.4 (high)', org: 'OpenAI', score: 1302 },
        { r: 19, name: 'GPT 5.5', org: 'OpenAI', score: 1297 },
        { r: 20, name: 'Gemini 3.6 Flash (high)', org: 'Google', score: 1297 },
        { r: 21, name: 'Gemini 3.1 Pro Preview', org: 'Google', score: 1296 },
        { r: 22, name: 'Claude Opus 4.8 (high)', org: 'Anthropic', score: 1295 },
        { r: 23, name: 'Muse Spark 1.1', org: 'Meta', score: 1292 },
        { r: 24, name: 'GPT 5.5 (high)', org: 'OpenAI', score: 1292 },
        { r: 25, name: 'GPT 5.4', org: 'OpenAI', score: 1292 },
        { r: 26, name: 'Claude Opus 4.8', org: 'Anthropic', score: 1288 },
        { r: 27, name: 'Grok 4.5', org: 'xAI', score: 1287 },
        { r: 28, name: 'Gemini 3 Flash', org: 'Google', score: 1285 },
        { r: 29, name: 'Claude Sonnet 4.6', org: 'Anthropic', score: 1283 },
        { r: 30, name: 'Kimi K2.6', org: 'Moonshot AI', score: 1282 }
      ],
      cn: [
        { r: 1, name: 'Qwen3.8 Max', org: 'Alibaba', score: 1314 },
        { r: 2, name: 'GLM 5.3 Flash', org: 'Zhipu AI', score: 1304 },
        { r: 3, name: 'Kimi K2.6', org: 'Moonshot AI', score: 1282 },
        { r: 4, name: 'Qwen3.7 Plus', org: 'Alibaba', score: 1281 },
        { r: 5, name: 'Dola Seed 2.0 Pro', org: 'ByteDance', score: 1274 },
        { r: 6, name: 'Qwen3.8 27B', org: 'Alibaba', score: 1270 },
        { r: 7, name: 'Kimi K2.5 Thinking', org: 'Moonshot AI', score: 1269 },
        { r: 8, name: 'MiMo V2.6 Flash', org: 'Xiaomi', score: 1265 },
        { r: 9, name: 'MiMo V2.6 Pro', org: 'Xiaomi', score: 1265 },
        { r: 10, name: 'GLM 5v Turbo', org: 'Zhipu AI', score: 1264 },
        { r: 11, name: 'Qwen3.5 397B A17B', org: 'Alibaba', score: 1262 },
        { r: 12, name: 'MiniMax M3', org: 'MiniMax', score: 1254 },
        { r: 13, name: 'Kimi K2.5 Instant', org: 'Moonshot AI', score: 1254 },
        { r: 14, name: 'ERNIE 5.0 Preview 1220', org: 'Baidu', score: 1248 },
        { r: 15, name: 'Qwen3 VL 235B A22B Instruct', org: 'Alibaba', score: 1247 },
        { r: 16, name: 'Qwen3.5 122B A10B', org: 'Alibaba', score: 1245 },
        { r: 17, name: 'MiMo V2.5', org: 'Xiaomi', score: 1245 },
        { r: 18, name: 'Qwen3.5 27B', org: 'Alibaba', score: 1240 },
        { r: 19, name: 'MiMo V2 Omni', org: 'Xiaomi', score: 1228 },
        { r: 20, name: 'Qwen VL Max 2025.08.13', org: 'Alibaba', score: 1212 }
      ],
      us: [
        { r: 1, name: 'Claude Fable 5 (high)', org: 'Anthropic', score: 1326 },
        { r: 2, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 1321 },
        { r: 3, name: 'Claude Fable 5.1 Max', org: 'Anthropic', score: 1319 },
        { r: 4, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1317 },
        { r: 5, name: 'Claude Opus 4.6 (high)', org: 'Anthropic', score: 1316 },
        { r: 6, name: 'Gemini 3.7 Flash (high)', org: 'Google', score: 1314 },
        { r: 7, name: 'Claude Opus 4.7 (high)', org: 'Anthropic', score: 1314 },
        { r: 8, name: 'Claude Opus 4.6', org: 'Anthropic', score: 1313 },
        { r: 9, name: 'Gemini 3.8 Flash (high)', org: 'Google', score: 1312 },
        { r: 10, name: 'Gemini 3.5 Flash (high)', org: 'Google', score: 1310 },
        { r: 11, name: 'Muse Spark 1.3 Max', org: 'Meta', score: 1310 },
        { r: 12, name: 'Gemini 3.5 Flash (medium)', org: 'Google', score: 1308 },
        { r: 13, name: 'Muse Spark', org: 'Meta', score: 1306 },
        { r: 14, name: 'Gemini 3 Pro', org: 'Google', score: 1305 },
        { r: 15, name: 'Muse Spark 1.2 (xhigh)', org: 'Meta', score: 1304 },
        { r: 16, name: 'GPT 5.4 (high)', org: 'OpenAI', score: 1302 },
        { r: 17, name: 'GPT 5.5', org: 'OpenAI', score: 1297 },
        { r: 18, name: 'Gemini 3.6 Flash (high)', org: 'Google', score: 1297 },
        { r: 19, name: 'Gemini 3.1 Pro Preview', org: 'Google', score: 1296 },
        { r: 20, name: 'Claude Opus 4.8 (high)', org: 'Anthropic', score: 1295 }
      ]
    }
  },
  {
    key: 't2i',
    label: { zh: '图片生成', en: 'Image Gen' },
    asOf: '2026-09',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'GPT Image 2.5 Sunburst', org: 'OpenAI', score: 1424 },
        { r: 2, name: 'GPT Image 2.5 Flare', org: 'OpenAI', score: 1401 },
        { r: 3, name: 'GPT Image 2 (medium)', org: 'OpenAI', score: 1383 },
        { r: 4, name: 'Mai Image 2.6', org: 'Microsoft', score: 1335 },
        { r: 5, name: 'Reve 2.1', org: 'Reve', score: 1302 },
        { r: 6, name: 'Grok Imagine Image 2.0 (low)', org: 'xAI', score: 1301 },
        { r: 7, name: 'Muse Image', org: 'Meta', score: 1276 },
        { r: 8, name: 'Reve 2.0', org: 'Reve', score: 1269 },
        { r: 9, name: 'Gemini 3.1 Flash Image (nano Banana 2) [web Search]', org: 'Google', score: 1261 },
        { r: 10, name: 'Seedream 5.0 Pro', org: 'ByteDance', score: 1256 },
        { r: 11, name: 'Qwen Image 3.0 Pro', org: 'Alibaba', score: 1256 },
        { r: 12, name: 'Mai Image 2.5', org: 'Microsoft', score: 1254 },
        { r: 13, name: 'Gemini 3.1 Flash Lite Image (nano Banana 2 Lite)', org: 'Google', score: 1250 },
        { r: 14, name: 'Gemini 3 Pro Image 2k (nano Banana Pro)', org: 'Google', score: 1247 },
        { r: 15, name: 'GPT Image 1.5 High Fidelity', org: 'OpenAI', score: 1238 },
        { r: 16, name: 'Gemini 3 Pro Image Preview (nano Banana Pro)', org: 'Google', score: 1234 },
        { r: 17, name: 'Qwen Image 2.1', org: 'Alibaba', score: 1228 },
        { r: 18, name: 'Ideogram 4.0 Quality', org: 'Ideogram', score: 1205 },
        { r: 19, name: 'Qwen Image 2.0 Pro 2026.06.22', org: 'Alibaba', score: 1192 },
        { r: 20, name: 'Uni 1.1 Max', org: 'Luma AI', score: 1189 },
        { r: 21, name: 'Mai Image 2', org: 'Microsoft', score: 1184 },
        { r: 22, name: 'Uni 1.1', org: 'Luma AI', score: 1183 },
        { r: 23, name: 'Grok Imagine Image', org: 'xAI', score: 1170 },
        { r: 24, name: 'Recraft V4.1 Utility Pro', org: 'Recraft', score: 1169 },
        { r: 25, name: 'Cosmos3 Super Text2Image (Agentic)', org: 'NVIDIA', score: 1165 },
        { r: 26, name: 'Grok Imagine Image Pro', org: 'xAI', score: 1162 },
        { r: 27, name: 'FLUX 2 Max', org: 'Black Forest Labs', score: 1162 },
        { r: 28, name: 'FLUX 2 Flex', org: 'Black Forest Labs', score: 1157 },
        { r: 29, name: 'Reve V1.5', org: 'Reve', score: 1155 },
        { r: 30, name: 'FLUX 2 Pro', org: 'Black Forest Labs', score: 1154 }
      ],
      cn: [
        { r: 1, name: 'Seedream 5.0 Pro', org: 'ByteDance', score: 1256 },
        { r: 2, name: 'Qwen Image 3.0 Pro', org: 'Alibaba', score: 1256 },
        { r: 3, name: 'Qwen Image 2.1', org: 'Alibaba', score: 1228 },
        { r: 4, name: 'Qwen Image 2.0 Pro 2026.06.22', org: 'Alibaba', score: 1192 },
        { r: 5, name: 'Hunyuan Image 3.0', org: 'Tencent', score: 1150 },
        { r: 6, name: 'Seedream 4.5', org: 'ByteDance', score: 1147 },
        { r: 7, name: 'Seedream 4 2k', org: 'ByteDance', score: 1140 },
        { r: 8, name: 'Seedream 5.0 Lite', org: 'ByteDance', score: 1138 },
        { r: 9, name: 'Wan2.6 T2i', org: 'Alibaba', score: 1137 },
        { r: 10, name: 'Qwen Image 2512', org: 'Alibaba', score: 1125 },
        { r: 11, name: 'Seedream 4 Fal', org: 'ByteDance', score: 1117 },
        { r: 12, name: 'Wan2.5 T2i Preview', org: 'Alibaba', score: 1116 },
        { r: 13, name: 'Seedream 4 High Res Fal', org: 'ByteDance', score: 1113 },
        { r: 14, name: 'Wan2.7 Image Pro', org: 'Alibaba', score: 1103 },
        { r: 15, name: 'Wan2.7 Image', org: 'Alibaba', score: 1101 },
        { r: 16, name: 'Z Image Turbo', org: 'Alibaba', score: 1084 },
        { r: 17, name: 'Seedream 3', org: 'ByteDance', score: 1082 },
        { r: 18, name: 'Qwen Image Prompt Extend', org: 'Alibaba', score: 1060 },
        { r: 19, name: 'Qwen Image', org: 'Alibaba', score: 1057 },
        { r: 20, name: 'GLM Image', org: 'Zhipu AI', score: 1012 }
      ],
      us: [
        { r: 1, name: 'GPT Image 2.5 Sunburst', org: 'OpenAI', score: 1424 },
        { r: 2, name: 'GPT Image 2.5 Flare', org: 'OpenAI', score: 1401 },
        { r: 3, name: 'GPT Image 2 (medium)', org: 'OpenAI', score: 1383 },
        { r: 4, name: 'Mai Image 2.6', org: 'Microsoft', score: 1335 },
        { r: 5, name: 'Reve 2.1', org: 'Reve', score: 1302 },
        { r: 6, name: 'Grok Imagine Image 2.0 (low)', org: 'xAI', score: 1301 },
        { r: 7, name: 'Muse Image', org: 'Meta', score: 1276 },
        { r: 8, name: 'Reve 2.0', org: 'Reve', score: 1269 },
        { r: 9, name: 'Gemini 3.1 Flash Image (nano Banana 2) [web Search]', org: 'Google', score: 1261 },
        { r: 10, name: 'Mai Image 2.5', org: 'Microsoft', score: 1254 },
        { r: 11, name: 'Gemini 3.1 Flash Lite Image (nano Banana 2 Lite)', org: 'Google', score: 1250 },
        { r: 12, name: 'Gemini 3 Pro Image 2k (nano Banana Pro)', org: 'Google', score: 1247 },
        { r: 13, name: 'GPT Image 1.5 High Fidelity', org: 'OpenAI', score: 1238 },
        { r: 14, name: 'Gemini 3 Pro Image Preview (nano Banana Pro)', org: 'Google', score: 1234 },
        { r: 15, name: 'Ideogram 4.0 Quality', org: 'Ideogram', score: 1205 },
        { r: 16, name: 'Uni 1.1 Max', org: 'Luma AI', score: 1189 },
        { r: 17, name: 'Mai Image 2', org: 'Microsoft', score: 1184 },
        { r: 18, name: 'Uni 1.1', org: 'Luma AI', score: 1183 },
        { r: 19, name: 'Grok Imagine Image', org: 'xAI', score: 1170 },
        { r: 20, name: 'Cosmos3 Super Text2Image (Agentic)', org: 'NVIDIA', score: 1165 }
      ]
    }
  },
  {
    key: 'imgedit',
    label: { zh: '图片编辑', en: 'Image Edit' },
    asOf: '2026-09',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'GPT Image 2.5 Sunburst', org: 'OpenAI', score: 1522 },
        { r: 2, name: 'GPT Image 2.5 Flare', org: 'OpenAI', score: 1478 },
        { r: 3, name: 'GPT Image 2 (medium)', org: 'OpenAI', score: 1461 },
        { r: 4, name: 'Grok Imagine Image 2.0 (low)', org: 'xAI', score: 1427 },
        { r: 5, name: 'Mai Image 2.6', org: 'Microsoft', score: 1427 },
        { r: 6, name: 'Muse Image', org: 'Meta', score: 1403 },
        { r: 7, name: 'Mai Image 2.5', org: 'Microsoft', score: 1401 },
        { r: 8, name: 'Seedream 5.0 Pro', org: 'ByteDance', score: 1394 },
        { r: 9, name: 'Grok Imagine Image Quality (20260519)', org: 'xAI', score: 1391 },
        { r: 10, name: 'Gemini 3 Pro Image 2k (nano Banana Pro)', org: 'Google', score: 1390 },
        { r: 11, name: 'ChatGPT Image Latest High Fidelity (20251216)', org: 'OpenAI', score: 1389 },
        { r: 12, name: 'Gemini 3.1 Flash Image (nano Banana 2) [web Search]', org: 'Google', score: 1387 },
        { r: 13, name: 'Gemini 3 Pro Image Preview (nano Banana Pro)', org: 'Google', score: 1386 },
        { r: 14, name: 'Reve 2.1', org: 'Reve', score: 1374 },
        { r: 15, name: 'GPT Image 1.5 High Fidelity', org: 'OpenAI', score: 1370 },
        { r: 16, name: 'Qwen Image 2.1', org: 'Alibaba', score: 1366 },
        { r: 17, name: 'Reve 2.0', org: 'Reve', score: 1359 },
        { r: 18, name: 'Ideogram 4.5', org: 'Ideogram', score: 1351 },
        { r: 19, name: 'Uni 1.1 Max', org: 'Luma AI', score: 1334 },
        { r: 20, name: 'Grok Imagine Image', org: 'xAI', score: 1329 },
        { r: 21, name: 'Uni 1.1', org: 'Luma AI', score: 1315 },
        { r: 22, name: 'Gemini 3.1 Flash Lite Image (nano Banana 2 Lite)', org: 'Google', score: 1314 },
        { r: 23, name: 'Qwen Image 2.0 Pro 2026.06.22', org: 'Alibaba', score: 1303 },
        { r: 24, name: 'Hunyuan Image 3.0 Instruct', org: 'Tencent', score: 1303 },
        { r: 25, name: 'Wan2.7 Image Pro', org: 'Alibaba', score: 1303 },
        { r: 26, name: 'Seedream 4.5', org: 'ByteDance', score: 1302 },
        { r: 27, name: 'Wan2.7 Image', org: 'Alibaba', score: 1301 },
        { r: 28, name: 'Seedream 5.0 Lite', org: 'ByteDance', score: 1294 },
        { r: 29, name: 'Gemini 2.5 Flash Image Preview (nano Banana)', org: 'Google', score: 1293 },
        { r: 30, name: 'Seedream 4 2k', org: 'ByteDance', score: 1270 }
      ],
      cn: [
        { r: 1, name: 'Seedream 5.0 Pro', org: 'ByteDance', score: 1394 },
        { r: 2, name: 'Qwen Image 2.1', org: 'Alibaba', score: 1366 },
        { r: 3, name: 'Qwen Image 2.0 Pro 2026.06.22', org: 'Alibaba', score: 1303 },
        { r: 4, name: 'Hunyuan Image 3.0 Instruct', org: 'Tencent', score: 1303 },
        { r: 5, name: 'Wan2.7 Image Pro', org: 'Alibaba', score: 1303 },
        { r: 6, name: 'Seedream 4.5', org: 'ByteDance', score: 1302 },
        { r: 7, name: 'Wan2.7 Image', org: 'Alibaba', score: 1301 },
        { r: 8, name: 'Seedream 5.0 Lite', org: 'ByteDance', score: 1294 },
        { r: 9, name: 'Seedream 4 2k', org: 'ByteDance', score: 1270 },
        { r: 10, name: 'Kling Image o1', org: 'Kuaishou', score: 1251 },
        { r: 11, name: 'Qwen Image Edit', org: 'Alibaba', score: 1241 },
        { r: 12, name: 'Qwen Image Edit 2511', org: 'Alibaba', score: 1234 },
        { r: 13, name: 'Wan2.6 Image', org: 'Alibaba', score: 1231 },
        { r: 14, name: 'Seedream 4 High Res Fal', org: 'ByteDance', score: 1217 },
        { r: 15, name: 'Seedream 4 Fal', org: 'ByteDance', score: 1210 },
        { r: 16, name: 'Wan2.5 I2i Preview', org: 'Alibaba', score: 1181 },
        { r: 17, name: 'Seededit 3.0', org: 'ByteDance', score: 1139 },
        { r: 18, name: 'Bagel', org: 'ByteDance', score: 1027 },
        { r: 19, name: 'Step1x Edit', org: 'StepFun', score: 998 }
      ],
      us: [
        { r: 1, name: 'GPT Image 2.5 Sunburst', org: 'OpenAI', score: 1522 },
        { r: 2, name: 'GPT Image 2.5 Flare', org: 'OpenAI', score: 1478 },
        { r: 3, name: 'GPT Image 2 (medium)', org: 'OpenAI', score: 1461 },
        { r: 4, name: 'Grok Imagine Image 2.0 (low)', org: 'xAI', score: 1427 },
        { r: 5, name: 'Mai Image 2.6', org: 'Microsoft', score: 1427 },
        { r: 6, name: 'Muse Image', org: 'Meta', score: 1403 },
        { r: 7, name: 'Mai Image 2.5', org: 'Microsoft', score: 1401 },
        { r: 8, name: 'Grok Imagine Image Quality (20260519)', org: 'xAI', score: 1391 },
        { r: 9, name: 'Gemini 3 Pro Image 2k (nano Banana Pro)', org: 'Google', score: 1390 },
        { r: 10, name: 'ChatGPT Image Latest High Fidelity (20251216)', org: 'OpenAI', score: 1389 },
        { r: 11, name: 'Gemini 3.1 Flash Image (nano Banana 2) [web Search]', org: 'Google', score: 1387 },
        { r: 12, name: 'Gemini 3 Pro Image Preview (nano Banana Pro)', org: 'Google', score: 1386 },
        { r: 13, name: 'Reve 2.1', org: 'Reve', score: 1374 },
        { r: 14, name: 'GPT Image 1.5 High Fidelity', org: 'OpenAI', score: 1370 },
        { r: 15, name: 'Reve 2.0', org: 'Reve', score: 1359 },
        { r: 16, name: 'Ideogram 4.5', org: 'Ideogram', score: 1351 },
        { r: 17, name: 'Uni 1.1 Max', org: 'Luma AI', score: 1334 },
        { r: 18, name: 'Grok Imagine Image', org: 'xAI', score: 1329 },
        { r: 19, name: 'Uni 1.1', org: 'Luma AI', score: 1315 },
        { r: 20, name: 'Gemini 3.1 Flash Lite Image (nano Banana 2 Lite)', org: 'Google', score: 1314 }
      ]
    }
  },
  {
    key: 't2v',
    label: { zh: '视频生成', en: 'Video Gen' },
    asOf: '2026-09',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'Gemini Omni 1.1 Flash', org: 'Google', score: 1516 },
        { r: 2, name: 'Gemini Omni Flash', org: 'Google', score: 1513 },
        { r: 3, name: 'FLUX 3 Video', org: 'Black Forest Labs', score: 1493 },
        { r: 4, name: 'Grok Imagine Video 1.5 Agent', org: 'xAI', score: 1492 },
        { r: 5, name: 'Dreamina Seedance 2.0 720p', org: 'ByteDance', score: 1479 },
        { r: 6, name: 'Wan3.0', org: 'Alibaba', score: 1476 },
        { r: 7, name: 'Dreamina Seedance 2.5 720p', org: 'ByteDance', score: 1474 },
        { r: 8, name: 'MiniMax H3', org: 'MiniMax', score: 1460 },
        { r: 9, name: 'Muse Video', org: 'Meta', score: 1456 },
        { r: 10, name: 'Happyhorse 1.0', org: 'Aorizon', score: 1427 },
        { r: 11, name: 'Sora 2 Pro', org: 'OpenAI', score: 1368 },
        { r: 12, name: 'Veo 3.1 Audio', org: 'Google', score: 1364 },
        { r: 13, name: 'Veo 3.1 Audio 1080p', org: 'Google', score: 1362 },
        { r: 14, name: 'Veo 3.1 Fast Audio', org: 'Google', score: 1362 },
        { r: 15, name: 'Veo 3.1 Fast Audio 1080p', org: 'Google', score: 1358 },
        { r: 16, name: 'Veo 3 Fast Audio', org: 'Google', score: 1348 },
        { r: 17, name: 'Sora 2', org: 'OpenAI', score: 1343 },
        { r: 18, name: 'Grok Imagine Video 720p', org: 'xAI', score: 1342 },
        { r: 19, name: 'Veo 3 Audio', org: 'Google', score: 1340 },
        { r: 20, name: 'Wan2.7 T2v', org: 'Alibaba', score: 1337 },
        { r: 21, name: 'Wan2.6 T2v', org: 'Alibaba', score: 1327 },
        { r: 22, name: 'Seedance V1.5 Pro', org: 'ByteDance', score: 1256 },
        { r: 23, name: 'Veo 3', org: 'Google', score: 1254 },
        { r: 24, name: 'Veo 3 Fast', org: 'Google', score: 1248 },
        { r: 25, name: 'Wan2.5 T2v Preview', org: 'Alibaba', score: 1245 },
        { r: 26, name: 'Pixverse V5.6', org: '', score: 1240 },
        { r: 27, name: 'Runway Gen 4.5', org: 'Runway', score: 1225 },
        { r: 28, name: 'Kling 2.5 Turbo 1080p', org: 'Kuaishou', score: 1220 },
        { r: 29, name: 'Kling 2.6 Pro', org: 'Kuaishou', score: 1216 },
        { r: 30, name: 'P Video', org: '', score: 1207 }
      ],
      cn: [
        { r: 1, name: 'Dreamina Seedance 2.0 720p', org: 'ByteDance', score: 1479 },
        { r: 2, name: 'Wan3.0', org: 'Alibaba', score: 1476 },
        { r: 3, name: 'Dreamina Seedance 2.5 720p', org: 'ByteDance', score: 1474 },
        { r: 4, name: 'MiniMax H3', org: 'MiniMax', score: 1460 },
        { r: 5, name: 'Wan2.7 T2v', org: 'Alibaba', score: 1337 },
        { r: 6, name: 'Wan2.6 T2v', org: 'Alibaba', score: 1327 },
        { r: 7, name: 'Seedance V1.5 Pro', org: 'ByteDance', score: 1256 },
        { r: 8, name: 'Wan2.5 T2v Preview', org: 'Alibaba', score: 1245 },
        { r: 9, name: 'Kling 2.5 Turbo 1080p', org: 'Kuaishou', score: 1220 },
        { r: 10, name: 'Kling 2.6 Pro', org: 'Kuaishou', score: 1216 },
        { r: 11, name: 'Hailuo 2.3', org: 'MiniMax', score: 1206 },
        { r: 12, name: 'Kling o1 Pro', org: 'Kuaishou', score: 1205 },
        { r: 13, name: 'Hailuo 02 Pro', org: 'MiniMax', score: 1198 },
        { r: 14, name: 'Seedance V1 Pro', org: 'ByteDance', score: 1191 },
        { r: 15, name: 'Hailuo 02 Standard', org: 'MiniMax', score: 1181 },
        { r: 16, name: 'Hunyuan Video 1.5', org: 'Tencent', score: 1169 },
        { r: 17, name: 'Kling V2.1 Master', org: 'Kuaishou', score: 1163 },
        { r: 18, name: 'Wan V2.2 A14B', org: 'Alibaba', score: 1132 },
        { r: 19, name: 'Seedance V1 Lite', org: 'ByteDance', score: 1113 }
      ],
      us: [
        { r: 1, name: 'Gemini Omni 1.1 Flash', org: 'Google', score: 1516 },
        { r: 2, name: 'Gemini Omni Flash', org: 'Google', score: 1513 },
        { r: 3, name: 'Grok Imagine Video 1.5 Agent', org: 'xAI', score: 1492 },
        { r: 4, name: 'Muse Video', org: 'Meta', score: 1456 },
        { r: 5, name: 'Sora 2 Pro', org: 'OpenAI', score: 1368 },
        { r: 6, name: 'Veo 3.1 Audio', org: 'Google', score: 1364 },
        { r: 7, name: 'Veo 3.1 Audio 1080p', org: 'Google', score: 1362 },
        { r: 8, name: 'Veo 3.1 Fast Audio', org: 'Google', score: 1362 },
        { r: 9, name: 'Veo 3.1 Fast Audio 1080p', org: 'Google', score: 1358 },
        { r: 10, name: 'Veo 3 Fast Audio', org: 'Google', score: 1348 },
        { r: 11, name: 'Sora 2', org: 'OpenAI', score: 1343 },
        { r: 12, name: 'Grok Imagine Video 720p', org: 'xAI', score: 1342 },
        { r: 13, name: 'Veo 3 Audio', org: 'Google', score: 1340 },
        { r: 14, name: 'Veo 3', org: 'Google', score: 1254 },
        { r: 15, name: 'Veo 3 Fast', org: 'Google', score: 1248 },
        { r: 16, name: 'Runway Gen 4.5', org: 'Runway', score: 1225 },
        { r: 17, name: 'Ray 3', org: 'Luma AI', score: 1206 },
        { r: 18, name: 'Veo 2', org: 'Google', score: 1164 },
        { r: 19, name: 'Sora', org: 'OpenAI', score: 1069 },
        { r: 20, name: 'Ray2', org: 'Luma AI', score: 1065 }
      ]
    }
  },
  {
    key: 'i2v',
    label: { zh: '图生视频', en: 'Image→Video' },
    asOf: '2026-09',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'MiniMax H3', org: 'MiniMax', score: 1495 },
        { r: 2, name: 'Gemini Omni 1.1 Flash', org: 'Google', score: 1488 },
        { r: 3, name: 'Wan3.0', org: 'Alibaba', score: 1480 },
        { r: 4, name: 'Dreamina Seedance 2.5 720p', org: 'ByteDance', score: 1477 },
        { r: 5, name: 'Dreamina Seedance 2.0 720p', org: 'ByteDance', score: 1475 },
        { r: 6, name: 'Gemini Omni Flash', org: 'Google', score: 1465 },
        { r: 7, name: 'Hidream o1 Video 1.0', org: 'HiDream', score: 1456 },
        { r: 8, name: 'Grok Imagine Video 1.5 720p', org: 'xAI', score: 1456 },
        { r: 9, name: 'FLUX 3 Video 20260811', org: 'Black Forest Labs', score: 1449 },
        { r: 10, name: 'Happyhorse 1.0', org: 'Aorizon', score: 1442 },
        { r: 11, name: 'Wan2.7 I2v', org: 'Alibaba', score: 1428 },
        { r: 12, name: 'Grok Imagine Video 720p', org: 'xAI', score: 1415 },
        { r: 13, name: 'Veo 3.1 Audio', org: 'Google', score: 1398 },
        { r: 14, name: 'Veo 3.1 Audio 1080p', org: 'Google', score: 1390 },
        { r: 15, name: 'Veo 3.1 Fast Audio', org: 'Google', score: 1385 },
        { r: 16, name: 'Grok Imagine Video 480p', org: 'xAI', score: 1385 },
        { r: 17, name: 'Veo 3.1 Fast Audio 1080p', org: 'Google', score: 1372 },
        { r: 18, name: 'Vidu Q3 Pro', org: 'Shengshu', score: 1363 },
        { r: 19, name: 'Kling V3 Pro', org: 'Kuaishou', score: 1354 },
        { r: 20, name: 'Veo 3 Audio', org: 'Google', score: 1331 },
        { r: 21, name: 'Veo 3 Fast Audio', org: 'Google', score: 1326 },
        { r: 22, name: 'Wan2.5 I2v Preview', org: 'Alibaba', score: 1321 },
        { r: 23, name: 'Wan2.6 I2v', org: 'Alibaba', score: 1310 },
        { r: 24, name: 'Seedance V1.5 Pro', org: 'ByteDance', score: 1307 },
        { r: 25, name: 'Pixverse V5.6', org: '', score: 1299 },
        { r: 26, name: 'Kling 2.6 Pro', org: 'Kuaishou', score: 1294 },
        { r: 27, name: 'Kling 2.5 Turbo 1080p', org: 'Kuaishou', score: 1276 },
        { r: 28, name: 'Seedance V1 Pro', org: 'ByteDance', score: 1273 },
        { r: 29, name: 'Hailuo 2.3', org: 'MiniMax', score: 1262 },
        { r: 30, name: 'Veo 3', org: 'Google', score: 1258 }
      ],
      cn: [
        { r: 1, name: 'MiniMax H3', org: 'MiniMax', score: 1495 },
        { r: 2, name: 'Wan3.0', org: 'Alibaba', score: 1480 },
        { r: 3, name: 'Dreamina Seedance 2.5 720p', org: 'ByteDance', score: 1477 },
        { r: 4, name: 'Dreamina Seedance 2.0 720p', org: 'ByteDance', score: 1475 },
        { r: 5, name: 'Wan2.7 I2v', org: 'Alibaba', score: 1428 },
        { r: 6, name: 'Vidu Q3 Pro', org: 'Shengshu', score: 1363 },
        { r: 7, name: 'Kling V3 Pro', org: 'Kuaishou', score: 1354 },
        { r: 8, name: 'Wan2.5 I2v Preview', org: 'Alibaba', score: 1321 },
        { r: 9, name: 'Wan2.6 I2v', org: 'Alibaba', score: 1310 },
        { r: 10, name: 'Seedance V1.5 Pro', org: 'ByteDance', score: 1307 },
        { r: 11, name: 'Kling 2.6 Pro', org: 'Kuaishou', score: 1294 },
        { r: 12, name: 'Kling 2.5 Turbo 1080p', org: 'Kuaishou', score: 1276 },
        { r: 13, name: 'Seedance V1 Pro', org: 'ByteDance', score: 1273 },
        { r: 14, name: 'Hailuo 2.3', org: 'MiniMax', score: 1262 },
        { r: 15, name: 'Vidu Q2 Turbo', org: 'Shengshu', score: 1244 },
        { r: 16, name: 'Kling V2.1 Master', org: 'Kuaishou', score: 1235 },
        { r: 17, name: 'Hailuo 02 Pro', org: 'MiniMax', score: 1229 },
        { r: 18, name: 'Kling V2.1 Standard', org: 'Kuaishou', score: 1229 },
        { r: 19, name: 'Hailuo 02 Standard', org: 'MiniMax', score: 1224 },
        { r: 20, name: 'Vidu Q2 Pro', org: 'Shengshu', score: 1223 }
      ],
      us: [
        { r: 1, name: 'Gemini Omni 1.1 Flash', org: 'Google', score: 1488 },
        { r: 2, name: 'Gemini Omni Flash', org: 'Google', score: 1465 },
        { r: 3, name: 'Grok Imagine Video 1.5 720p', org: 'xAI', score: 1456 },
        { r: 4, name: 'Grok Imagine Video 720p', org: 'xAI', score: 1415 },
        { r: 5, name: 'Veo 3.1 Audio', org: 'Google', score: 1398 },
        { r: 6, name: 'Veo 3.1 Audio 1080p', org: 'Google', score: 1390 },
        { r: 7, name: 'Veo 3.1 Fast Audio', org: 'Google', score: 1385 },
        { r: 8, name: 'Grok Imagine Video 480p', org: 'xAI', score: 1385 },
        { r: 9, name: 'Veo 3.1 Fast Audio 1080p', org: 'Google', score: 1372 },
        { r: 10, name: 'Veo 3 Audio', org: 'Google', score: 1331 },
        { r: 11, name: 'Veo 3 Fast Audio', org: 'Google', score: 1326 },
        { r: 12, name: 'Veo 3', org: 'Google', score: 1258 },
        { r: 13, name: 'Veo 3 Fast', org: 'Google', score: 1257 },
        { r: 14, name: 'Ray 3', org: 'Luma AI', score: 1226 },
        { r: 15, name: 'Veo 2', org: 'Google', score: 1166 },
        { r: 16, name: 'Ray2', org: 'Luma AI', score: 1108 },
        { r: 17, name: 'Runway Gen4 Turbo', org: 'Runway', score: 1052 },
        { r: 18, name: 'Pika V2.2', org: 'Pika', score: 997 }
      ]
    }
  },
  {
    key: 'webdev',
    label: { zh: '网页开发', en: 'Web Dev' },
    asOf: '2026-09',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'Claude Opus 5.5 Max', org: 'Anthropic', score: 1818 },
        { r: 2, name: 'GPT 6 Astra Max', org: 'OpenAI', score: 1789 },
        { r: 3, name: 'GPT 6.1 Sol Max', org: 'OpenAI', score: 1759 },
        { r: 4, name: 'Claude Fable 5.1 Max', org: 'Anthropic', score: 1751 },
        { r: 5, name: 'Claude Sonnet 5.5 (high)', org: 'Anthropic', score: 1709 },
        { r: 6, name: 'Claude Opus 5 Max', org: 'Anthropic', score: 1694 },
        { r: 7, name: 'GPT 6 Sol Max', org: 'OpenAI', score: 1689 },
        { r: 8, name: 'Gemini 4 Argon (high)', org: 'Google', score: 1679 },
        { r: 9, name: 'Qwen3.8 Max', org: 'Alibaba', score: 1671 },
        { r: 10, name: 'Qwen3.8 Max 0902', org: 'Alibaba', score: 1670 },
        { r: 11, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 1660 },
        { r: 12, name: 'Kimi K3 Max', org: 'Moonshot AI', score: 1658 },
        { r: 13, name: 'Muse Spark 1.3 Max', org: 'Meta', score: 1655 },
        { r: 14, name: 'Qwen3.8 Flash Next', org: 'Alibaba', score: 1638 },
        { r: 15, name: 'Grok 4.7 (xhigh)', org: 'xAI', score: 1636 },
        { r: 16, name: 'HY4 Preview', org: 'Tencent', score: 1633 },
        { r: 17, name: 'Claude Fable 5 (high)', org: 'Anthropic', score: 1626 },
        { r: 18, name: 'Muse Spark 1.3 (xhigh)', org: 'Meta', score: 1623 },
        { r: 19, name: 'GLM 5.3 Max', org: 'Zhipu AI', score: 1622 },
        { r: 20, name: 'Grok 4.6 (high)', org: 'xAI', score: 1620 },
        { r: 21, name: 'DeepSeek V4.1 Flash Max', org: 'DeepSeek', score: 1620 },
        { r: 22, name: 'GPT 5.6 Sol xHigh (codex Harness)', org: 'OpenAI', score: 1619 },
        { r: 23, name: 'MiMo V2.6 Pro', org: 'Xiaomi', score: 1619 },
        { r: 24, name: 'GLM 5.3 Flash', org: 'Zhipu AI', score: 1615 },
        { r: 25, name: 'GLM 5.2 Max', org: 'Zhipu AI', score: 1605 },
        { r: 26, name: 'Gemini 3.7 Flash (high)', org: 'Google', score: 1592 },
        { r: 27, name: 'Qwen3.8 27B', org: 'Alibaba', score: 1590 },
        { r: 28, name: 'Gemini 3.8 Flash (high)', org: 'Google', score: 1583 },
        { r: 29, name: 'DeepSeek V4 Pro High 20260813', org: 'DeepSeek', score: 1582 },
        { r: 30, name: 'GPT 6 Luna Max', org: 'OpenAI', score: 1582 }
      ],
      cn: [
        { r: 1, name: 'Qwen3.8 Max', org: 'Alibaba', score: 1671 },
        { r: 2, name: 'Qwen3.8 Max 0902', org: 'Alibaba', score: 1670 },
        { r: 3, name: 'Kimi K3 Max', org: 'Moonshot AI', score: 1658 },
        { r: 4, name: 'Qwen3.8 Flash Next', org: 'Alibaba', score: 1638 },
        { r: 5, name: 'HY4 Preview', org: 'Tencent', score: 1633 },
        { r: 6, name: 'GLM 5.3 Max', org: 'Zhipu AI', score: 1622 },
        { r: 7, name: 'DeepSeek V4.1 Flash Max', org: 'DeepSeek', score: 1620 },
        { r: 8, name: 'MiMo V2.6 Pro', org: 'Xiaomi', score: 1619 },
        { r: 9, name: 'GLM 5.3 Flash', org: 'Zhipu AI', score: 1615 },
        { r: 10, name: 'GLM 5.2 Max', org: 'Zhipu AI', score: 1605 },
        { r: 11, name: 'Qwen3.8 27B', org: 'Alibaba', score: 1590 },
        { r: 12, name: 'DeepSeek V4 Pro High 20260813', org: 'DeepSeek', score: 1582 },
        { r: 13, name: 'DeepSeek V4 Flash (high)', org: 'DeepSeek', score: 1581 },
        { r: 14, name: 'Step 5 Preview (high)', org: 'StepFun', score: 1570 },
        { r: 15, name: 'Seed 2.1 Pro Preview', org: 'ByteDance', score: 1517 },
        { r: 16, name: 'Qwen3.7 Max 20260517', org: 'Alibaba', score: 1515 },
        { r: 17, name: 'Kimi K2.6', org: 'Moonshot AI', score: 1509 },
        { r: 18, name: 'GLM 5.1', org: 'Zhipu AI', score: 1508 },
        { r: 19, name: 'HY3', org: 'Tencent', score: 1508 },
        { r: 20, name: 'MiniMax M3', org: 'MiniMax', score: 1482 }
      ],
      us: [
        { r: 1, name: 'Claude Opus 5.5 Max', org: 'Anthropic', score: 1818 },
        { r: 2, name: 'GPT 6 Astra Max', org: 'OpenAI', score: 1789 },
        { r: 3, name: 'GPT 6.1 Sol Max', org: 'OpenAI', score: 1759 },
        { r: 4, name: 'Claude Fable 5.1 Max', org: 'Anthropic', score: 1751 },
        { r: 5, name: 'Claude Sonnet 5.5 (high)', org: 'Anthropic', score: 1709 },
        { r: 6, name: 'Claude Opus 5 Max', org: 'Anthropic', score: 1694 },
        { r: 7, name: 'GPT 6 Sol Max', org: 'OpenAI', score: 1689 },
        { r: 8, name: 'Gemini 4 Argon (high)', org: 'Google', score: 1679 },
        { r: 9, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 1660 },
        { r: 10, name: 'Muse Spark 1.3 Max', org: 'Meta', score: 1655 },
        { r: 11, name: 'Grok 4.7 (xhigh)', org: 'xAI', score: 1636 },
        { r: 12, name: 'Claude Fable 5 (high)', org: 'Anthropic', score: 1626 },
        { r: 13, name: 'Muse Spark 1.3 (xhigh)', org: 'Meta', score: 1623 },
        { r: 14, name: 'Grok 4.6 (high)', org: 'xAI', score: 1620 },
        { r: 15, name: 'GPT 5.6 Sol xHigh (codex Harness)', org: 'OpenAI', score: 1619 },
        { r: 16, name: 'Gemini 3.7 Flash (high)', org: 'Google', score: 1592 },
        { r: 17, name: 'Gemini 3.8 Flash (high)', org: 'Google', score: 1583 },
        { r: 18, name: 'GPT 6 Luna Max', org: 'OpenAI', score: 1582 },
        { r: 19, name: 'Claude Opus 4.7 (high)', org: 'Anthropic', score: 1557 },
        { r: 20, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1556 }
      ]
    }
  },
  {
    key: 'search',
    label: { zh: '联网搜索', en: 'Search' },
    asOf: '2026-08',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'GPT 5.6 Sol (xhigh)', org: 'OpenAI', score: 1257 },
        { r: 2, name: 'Claude Opus 4.6 Search', org: 'Anthropic', score: 1253 },
        { r: 3, name: 'GPT 5.5 Search', org: 'OpenAI', score: 1242 },
        { r: 4, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1233 },
        { r: 5, name: 'Claude Fable 5', org: 'Anthropic', score: 1230 },
        { r: 6, name: 'ERNIE 5.1', org: 'Baidu', score: 1227 },
        { r: 7, name: 'Claude Sonnet 4.6 Search', org: 'Anthropic', score: 1221 },
        { r: 8, name: 'Grok 4.5', org: 'xAI', score: 1213 },
        { r: 9, name: 'Gemini 3.1 Pro Grounding', org: 'Google', score: 1210 },
        { r: 10, name: 'Gemini 3 Pro Grounding', org: 'Google', score: 1207 },
        { r: 11, name: 'GPT 5.2 Search', org: 'OpenAI', score: 1207 },
        { r: 12, name: 'Claude Opus 4.8', org: 'Anthropic', score: 1204 },
        { r: 13, name: 'Grok 4.20 Multi Agent Beta 0309', org: 'xAI', score: 1204 },
        { r: 14, name: 'GPT 5.1 Search', org: 'OpenAI', score: 1199 },
        { r: 15, name: 'Gemini 3 Flash Grounding', org: 'Google', score: 1198 },
        { r: 16, name: 'GPT 5.4 Search', org: 'OpenAI', score: 1197 },
        { r: 17, name: 'Claude Sonnet 5 Search', org: 'Anthropic', score: 1194 },
        { r: 18, name: 'Grok 4.20 Beta1', org: 'xAI', score: 1189 },
        { r: 19, name: 'Claude Opus 4.5 Search', org: 'Anthropic', score: 1180 },
        { r: 20, name: 'GPT 5.2 Search Non Reasoning', org: 'OpenAI', score: 1172 },
        { r: 21, name: 'Grok 4.1 Fast Search', org: 'xAI', score: 1171 },
        { r: 22, name: 'Grok 4 Fast Search', org: 'xAI', score: 1171 },
        { r: 23, name: 'Grok 4.3', org: 'xAI', score: 1165 },
        { r: 24, name: 'Claude Sonnet 4.5 Search', org: 'Anthropic', score: 1158 },
        { r: 25, name: 'Claude Opus 4.1 Search', org: 'Anthropic', score: 1148 },
        { r: 26, name: 'o3 Search', org: 'OpenAI', score: 1144 },
        { r: 27, name: 'Gemini 2.5 Pro Grounding', org: 'Google', score: 1142 },
        { r: 28, name: 'Grok 4 Search', org: 'xAI', score: 1142 },
        { r: 29, name: 'Ppl Sonar Reasoning Pro (high)', org: 'Perplexity', score: 1139 },
        { r: 30, name: 'GPT 5 Search', org: 'OpenAI', score: 1133 }
      ],
      cn: [
        { r: 1, name: 'ERNIE 5.1', org: 'Baidu', score: 1227 }
      ],
      us: [
        { r: 1, name: 'GPT 5.6 Sol (xhigh)', org: 'OpenAI', score: 1257 },
        { r: 2, name: 'Claude Opus 4.6 Search', org: 'Anthropic', score: 1253 },
        { r: 3, name: 'GPT 5.5 Search', org: 'OpenAI', score: 1242 },
        { r: 4, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1233 },
        { r: 5, name: 'Claude Fable 5', org: 'Anthropic', score: 1230 },
        { r: 6, name: 'Claude Sonnet 4.6 Search', org: 'Anthropic', score: 1221 },
        { r: 7, name: 'Grok 4.5', org: 'xAI', score: 1213 },
        { r: 8, name: 'Gemini 3.1 Pro Grounding', org: 'Google', score: 1210 },
        { r: 9, name: 'Gemini 3 Pro Grounding', org: 'Google', score: 1207 },
        { r: 10, name: 'GPT 5.2 Search', org: 'OpenAI', score: 1207 },
        { r: 11, name: 'Claude Opus 4.8', org: 'Anthropic', score: 1204 },
        { r: 12, name: 'Grok 4.20 Multi Agent Beta 0309', org: 'xAI', score: 1204 },
        { r: 13, name: 'GPT 5.1 Search', org: 'OpenAI', score: 1199 },
        { r: 14, name: 'Gemini 3 Flash Grounding', org: 'Google', score: 1198 },
        { r: 15, name: 'GPT 5.4 Search', org: 'OpenAI', score: 1197 },
        { r: 16, name: 'Claude Sonnet 5 Search', org: 'Anthropic', score: 1194 },
        { r: 17, name: 'Grok 4.20 Beta1', org: 'xAI', score: 1189 },
        { r: 18, name: 'Claude Opus 4.5 Search', org: 'Anthropic', score: 1180 },
        { r: 19, name: 'GPT 5.2 Search Non Reasoning', org: 'OpenAI', score: 1172 },
        { r: 20, name: 'Grok 4.1 Fast Search', org: 'xAI', score: 1171 }
      ]
    }
  },
  {
    key: 'doc',
    label: { zh: '文档理解', en: 'Document' },
    asOf: '2026-09',
    metric: { zh: 'Arena 评分（人类盲测 Elo）', en: 'Arena Score (blind-test Elo)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 0,
    items: {
      global: [
        { r: 1, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 1516 },
        { r: 2, name: 'Claude Fable 5.1 Max', org: 'Anthropic', score: 1513 },
        { r: 3, name: 'Claude Opus 4.6 (high)', org: 'Anthropic', score: 1507 },
        { r: 4, name: 'Claude Opus 4.6', org: 'Anthropic', score: 1507 },
        { r: 5, name: 'Claude Fable 5', org: 'Anthropic', score: 1496 },
        { r: 6, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1495 },
        { r: 7, name: 'Claude Opus 4.7 (high)', org: 'Anthropic', score: 1495 },
        { r: 8, name: 'GPT 5.5', org: 'OpenAI', score: 1486 },
        { r: 9, name: 'GPT 5.5 (high)', org: 'OpenAI', score: 1484 },
        { r: 10, name: 'GPT 5.6 Sol (xhigh)', org: 'OpenAI', score: 1483 },
        { r: 11, name: 'Claude Sonnet 4.6', org: 'Anthropic', score: 1482 },
        { r: 12, name: 'Claude Opus 4.8 (high)', org: 'Anthropic', score: 1475 },
        { r: 13, name: 'GPT 5.6 Terra (xhigh)', org: 'OpenAI', score: 1472 },
        { r: 14, name: 'GPT 5.4', org: 'OpenAI', score: 1471 },
        { r: 15, name: 'Muse Spark 1.3 Max', org: 'Meta', score: 1471 },
        { r: 16, name: 'GPT 6 Astra Max', org: 'OpenAI', score: 1468 },
        { r: 17, name: 'Claude Sonnet 5 (high)', org: 'Anthropic', score: 1466 },
        { r: 18, name: 'Muse Spark 1.1', org: 'Meta', score: 1465 },
        { r: 19, name: 'Claude Opus 4.8', org: 'Anthropic', score: 1464 },
        { r: 20, name: 'Gemini 3.5 Flash (medium)', org: 'Google', score: 1463 },
        { r: 21, name: 'Claude Opus 4.5 20251101', org: 'Anthropic', score: 1462 },
        { r: 22, name: 'Gemini 3.5 Flash (high)', org: 'Google', score: 1461 },
        { r: 23, name: 'GPT 5.6 Luna (xhigh)', org: 'OpenAI', score: 1457 },
        { r: 24, name: 'Gemini 3.6 Flash (high)', org: 'Google', score: 1456 },
        { r: 25, name: 'Grok 4.6 (high)', org: 'xAI', score: 1452 },
        { r: 26, name: 'Grok 4.5', org: 'xAI', score: 1452 },
        { r: 27, name: 'Kimi K2.6', org: 'Moonshot AI', score: 1451 },
        { r: 28, name: 'Claude Sonnet 4.5 20250929', org: 'Anthropic', score: 1450 },
        { r: 29, name: 'Muse Spark', org: 'Meta', score: 1444 },
        { r: 30, name: 'Qwen3.7 Plus', org: 'Alibaba', score: 1444 }
      ],
      cn: [
        { r: 1, name: 'Kimi K2.6', org: 'Moonshot AI', score: 1451 },
        { r: 2, name: 'Qwen3.7 Plus', org: 'Alibaba', score: 1444 },
        { r: 3, name: 'MiniMax M3', org: 'MiniMax', score: 1435 },
        { r: 4, name: 'Kimi K2.5 Thinking', org: 'Moonshot AI', score: 1430 },
        { r: 5, name: 'GLM 5v Turbo', org: 'Zhipu AI', score: 1416 }
      ],
      us: [
        { r: 1, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 1516 },
        { r: 2, name: 'Claude Fable 5.1 Max', org: 'Anthropic', score: 1513 },
        { r: 3, name: 'Claude Opus 4.6 (high)', org: 'Anthropic', score: 1507 },
        { r: 4, name: 'Claude Opus 4.6', org: 'Anthropic', score: 1507 },
        { r: 5, name: 'Claude Fable 5', org: 'Anthropic', score: 1496 },
        { r: 6, name: 'Claude Opus 4.7', org: 'Anthropic', score: 1495 },
        { r: 7, name: 'Claude Opus 4.7 (high)', org: 'Anthropic', score: 1495 },
        { r: 8, name: 'GPT 5.5', org: 'OpenAI', score: 1486 },
        { r: 9, name: 'GPT 5.5 (high)', org: 'OpenAI', score: 1484 },
        { r: 10, name: 'GPT 5.6 Sol (xhigh)', org: 'OpenAI', score: 1483 },
        { r: 11, name: 'Claude Sonnet 4.6', org: 'Anthropic', score: 1482 },
        { r: 12, name: 'Claude Opus 4.8 (high)', org: 'Anthropic', score: 1475 },
        { r: 13, name: 'GPT 5.6 Terra (xhigh)', org: 'OpenAI', score: 1472 },
        { r: 14, name: 'GPT 5.4', org: 'OpenAI', score: 1471 },
        { r: 15, name: 'Muse Spark 1.3 Max', org: 'Meta', score: 1471 },
        { r: 16, name: 'GPT 6 Astra Max', org: 'OpenAI', score: 1468 },
        { r: 17, name: 'Claude Sonnet 5 (high)', org: 'Anthropic', score: 1466 },
        { r: 18, name: 'Muse Spark 1.1', org: 'Meta', score: 1465 },
        { r: 19, name: 'Claude Opus 4.8', org: 'Anthropic', score: 1464 },
        { r: 20, name: 'Gemini 3.5 Flash (medium)', org: 'Google', score: 1463 }
      ]
    }
  },
  {
    key: 'agent',
    label: { zh: '智能体', en: 'Agent' },
    asOf: '2026-09',
    metric: { zh: 'Agent 优势分（真实会话盲测）', en: 'Agent advantage score (live sessions)' },
    sourceUrl: 'https://lmarena.ai/leaderboard/',
    digits: 4,
    items: {
      global: [
        { r: 1, name: 'Claude Fable 5.1 (max)', org: 'Anthropic', score: 0.1455 },
        { r: 2, name: 'Claude Opus 5.5 (high)', org: 'Anthropic', score: 0.1378 },
        { r: 3, name: 'GPT 6 Astra (max)', org: 'OpenAI', score: 0.1218 },
        { r: 4, name: 'GPT 6 Sol (max)', org: 'OpenAI', score: 0.1065 },
        { r: 5, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 0.0876 },
        { r: 6, name: 'Claude Opus 5 (max)', org: 'Anthropic', score: 0.0855 },
        { r: 7, name: 'Claude Fable 5 (high)', org: 'Anthropic', score: 0.0837 },
        { r: 8, name: 'Gemini 4 Argon (high)', org: 'Google', score: 0.0792 },
        { r: 9, name: 'GPT 5.6 Sol (xhigh)', org: 'OpenAI', score: 0.0705 },
        { r: 10, name: 'Claude Opus 4.8 (high)', org: 'Anthropic', score: 0.0692 },
        { r: 11, name: 'Claude Sonnet 5 (high)', org: 'Anthropic', score: 0.0481 },
        { r: 12, name: 'HY4 Preview', org: 'Tencent', score: 0.0424 },
        { r: 13, name: 'Muse Spark 1.3 (max)', org: 'Meta', score: 0.0419 },
        { r: 14, name: 'GPT 5.5 (xhigh)', org: 'OpenAI', score: 0.0412 },
        { r: 15, name: 'DeepSeek V4.1 Flash (max)', org: 'DeepSeek', score: 0.0401 },
        { r: 16, name: 'Kimi K3 (max)', org: 'Moonshot AI', score: 0.0398 },
        { r: 17, name: 'Grok 4.7 (xhigh)', org: 'xAI', score: 0.0364 },
        { r: 18, name: 'GLM 5.2 (max)', org: 'Zhipu AI', score: 0.0364 },
        { r: 19, name: 'Gemini 3.8 Flash (high)', org: 'Google', score: 0.0296 },
        { r: 20, name: 'Qwen3.8 Max', org: 'Alibaba', score: 0.0280 },
        { r: 21, name: 'GLM 5.3 (max)', org: 'Zhipu AI', score: 0.0257 },
        { r: 22, name: 'GPT 6 Luna (max)', org: 'OpenAI', score: 0.0168 },
        { r: 23, name: 'DeepSeek V4 Pro (high) (0813)', org: 'DeepSeek', score: 0.0129 },
        { r: 24, name: 'Grok 4.6 (xhigh)', org: 'xAI', score: 0.0116 },
        { r: 25, name: 'GPT 5.5', org: 'OpenAI', score: 0.0113 },
        { r: 26, name: 'Grok 4.5', org: 'xAI', score: 0.0111 },
        { r: 27, name: 'GPT 5.4 (high)', org: 'OpenAI', score: 0.0091 },
        { r: 28, name: 'GPT 5.6 Terra (xhigh)', org: 'OpenAI', score: 0.0083 },
        { r: 29, name: 'GLM 5.3 Flash', org: 'Zhipu AI', score: -0.0028 },
        { r: 30, name: 'Qwen3.8 Flash Next', org: 'Alibaba', score: -0.0079 }
      ],
      cn: [
        { r: 1, name: 'HY4 Preview', org: 'Tencent', score: 0.0424 },
        { r: 2, name: 'DeepSeek V4.1 Flash (max)', org: 'DeepSeek', score: 0.0401 },
        { r: 3, name: 'Kimi K3 (max)', org: 'Moonshot AI', score: 0.0398 },
        { r: 4, name: 'GLM 5.2 (max)', org: 'Zhipu AI', score: 0.0364 },
        { r: 5, name: 'Qwen3.8 Max', org: 'Alibaba', score: 0.0280 },
        { r: 6, name: 'GLM 5.3 (max)', org: 'Zhipu AI', score: 0.0257 },
        { r: 7, name: 'DeepSeek V4 Pro (high) (0813)', org: 'DeepSeek', score: 0.0129 },
        { r: 8, name: 'GLM 5.3 Flash', org: 'Zhipu AI', score: -0.0028 },
        { r: 9, name: 'Qwen3.8 Flash Next', org: 'Alibaba', score: -0.0079 },
        { r: 10, name: 'Qwen 3.8 27B', org: 'Alibaba', score: -0.0161 },
        { r: 11, name: 'Qwen3.7 Max', org: 'Alibaba', score: -0.0520 },
        { r: 12, name: 'HY3', org: 'Tencent', score: -0.0570 },
        { r: 13, name: 'MiniMax M3', org: 'MiniMax', score: -0.0671 },
        { r: 14, name: 'MiMo V2.5 Pro', org: 'Xiaomi', score: -0.0723 },
        { r: 15, name: 'Qwen3.7 Plus', org: 'Alibaba', score: -0.0728 }
      ],
      us: [
        { r: 1, name: 'Claude Fable 5.1 (max)', org: 'Anthropic', score: 0.1455 },
        { r: 2, name: 'Claude Opus 5.5 (high)', org: 'Anthropic', score: 0.1378 },
        { r: 3, name: 'GPT 6 Astra (max)', org: 'OpenAI', score: 0.1218 },
        { r: 4, name: 'GPT 6 Sol (max)', org: 'OpenAI', score: 0.1065 },
        { r: 5, name: 'Claude Opus 5 (high)', org: 'Anthropic', score: 0.0876 },
        { r: 6, name: 'Claude Opus 5 (max)', org: 'Anthropic', score: 0.0855 },
        { r: 7, name: 'Claude Fable 5 (high)', org: 'Anthropic', score: 0.0837 },
        { r: 8, name: 'Gemini 4 Argon (high)', org: 'Google', score: 0.0792 },
        { r: 9, name: 'GPT 5.6 Sol (xhigh)', org: 'OpenAI', score: 0.0705 },
        { r: 10, name: 'Claude Opus 4.8 (high)', org: 'Anthropic', score: 0.0692 },
        { r: 11, name: 'Claude Sonnet 5 (high)', org: 'Anthropic', score: 0.0481 },
        { r: 12, name: 'Muse Spark 1.3 (max)', org: 'Meta', score: 0.0419 },
        { r: 13, name: 'GPT 5.5 (xhigh)', org: 'OpenAI', score: 0.0412 },
        { r: 14, name: 'Grok 4.7 (xhigh)', org: 'xAI', score: 0.0364 },
        { r: 15, name: 'Gemini 3.8 Flash (high)', org: 'Google', score: 0.0296 },
        { r: 16, name: 'GPT 6 Luna (max)', org: 'OpenAI', score: 0.0168 },
        { r: 17, name: 'Grok 4.6 (xhigh)', org: 'xAI', score: 0.0116 },
        { r: 18, name: 'GPT 5.5', org: 'OpenAI', score: 0.0113 },
        { r: 19, name: 'Grok 4.5', org: 'xAI', score: 0.0111 },
        { r: 20, name: 'GPT 5.4 (high)', org: 'OpenAI', score: 0.0091 }
      ]
    }
  },
  {
    key: 'swe',
    label: { zh: '编程实测', en: 'SWE-bench' },
    asOf: '2026-10',
    metric: { zh: 'SWE-bench Verified 官方', en: 'SWE-bench Verified (official)' },
    sourceUrl: 'https://www.swebench.com/',
    digits: 1,
    items: {
      global: [
        { r: 1, name: 'Claude 4.5 Opus', org: 'Anthropic', score: 79.2 },
        { r: 2, name: 'Doubao Seed Code', org: 'ByteDance', score: 78.8 },
        { r: 3, name: 'Gemini 3 Pro Preview', org: 'Google DeepMind', score: 77.4 },
        { r: 4, name: 'Claude 4 Sonnet', org: 'Anthropic', score: 76.8 },
        { r: 5, name: 'Gemini 3 Flash', org: 'Google DeepMind', score: 75.8 },
        { r: 6, name: 'MiniMax M2.5', org: 'MiniMax', score: 75.8 },
        { r: 7, name: 'Claude 4.6 Opus', org: 'Anthropic', score: 75.6 },
        { r: 8, name: 'Claude Sonnet 4', org: 'Anthropic', score: 74.8 },
        { r: 9, name: 'Claude 4.5 Sonnet', org: 'Anthropic', score: 74.8 },
        { r: 10, name: 'GPT 5', org: 'OpenAI', score: 74.4 },
        { r: 11, name: 'Claude 4 Opus', org: 'Anthropic', score: 73.2 },
        { r: 12, name: 'GLM 5', org: 'Z-AI', score: 72.8 },
        { r: 13, name: 'GPT 5.2', org: 'OpenAI', score: 72.8 },
        { r: 14, name: 'GPT 5.2 Codex', org: 'OpenAI', score: 72.8 },
        { r: 15, name: 'Kimi K2', org: 'Moonshot AI', score: 71.2 },
        { r: 16, name: 'Kimi K2.5', org: 'Moonshot AI', score: 70.8 },
        { r: 17, name: 'DeepSeek V3.2', org: 'DeepSeek', score: 70.0 },
        { r: 18, name: 'Qwen3 Coder 480B A35B Instruct', org: 'Qwen', score: 69.6 },
        { r: 19, name: 'Gemini 3 Pro', org: 'Google DeepMind', score: 69.6 },
        { r: 20, name: 'GLM 4.6', org: 'Z.ai', score: 68.2 },
        { r: 21, name: 'Claude 4.5 Haiku', org: 'Anthropic', score: 66.6 },
        { r: 22, name: 'Claude 3.7 Sonnet', org: 'Anthropic', score: 66.4 },
        { r: 23, name: 'GPT 5.1', org: 'OpenAI', score: 66.0 },
        { r: 24, name: 'GPT 5.1 Codex', org: 'OpenAI', score: 66.0 },
        { r: 25, name: 'o1 Preview', org: 'OpenAI', score: 64.6 },
        { r: 26, name: 'o4 Mini', org: 'OpenAI', score: 64.6 },
        { r: 27, name: 'GLM 4.5', org: 'Z.ai', score: 64.2 },
        { r: 28, name: 'Claude 3.5 Sonnet', org: 'Anthropic', score: 63.4 },
        { r: 29, name: 'Kimi K2 Thinking', org: 'Moonshot AI', score: 63.4 },
        { r: 30, name: 'Claude 3.7 Sonnet W/ Review Heavy', org: 'Anthropic', score: 62.4 }
      ],
      cn: [
        { r: 1, name: 'Doubao Seed Code', org: 'ByteDance', score: 78.8 },
        { r: 2, name: 'MiniMax M2.5', org: 'MiniMax', score: 75.8 },
        { r: 3, name: 'GLM 5', org: 'Z-AI', score: 72.8 },
        { r: 4, name: 'Kimi K2', org: 'Moonshot AI', score: 71.2 },
        { r: 5, name: 'Kimi K2.5', org: 'Moonshot AI', score: 70.8 },
        { r: 6, name: 'DeepSeek V3.2', org: 'DeepSeek', score: 70.0 },
        { r: 7, name: 'Qwen3 Coder 480B A35B Instruct', org: 'Qwen', score: 69.6 },
        { r: 8, name: 'GLM 4.6', org: 'Z.ai', score: 68.2 },
        { r: 9, name: 'GLM 4.5', org: 'Z.ai', score: 64.2 },
        { r: 10, name: 'Kimi K2 Thinking', org: 'Moonshot AI', score: 63.4 },
        { r: 11, name: 'MiniMax M2', org: 'MiniMax', score: 61.0 },
        { r: 12, name: 'Qwen3 Coder 30B A3B Instruct', org: 'Qwen', score: 60.4 },
        { r: 13, name: 'DeepSeek V3.2 Reasoner', org: 'DeepSeek', score: 60.0 },
        { r: 14, name: 'Kimi K2 Instruct', org: 'Moonshot AI', score: 53.4 },
        { r: 15, name: 'TTS(Bo8)', org: 'Qwen', score: 47.0 },
        { r: 16, name: 'DeepSeek V3 0324', org: 'DeepSeek', score: 42.0 },
        { r: 17, name: 'SWE Agent LM 32B', org: 'Qwen', score: 40.2 },
        { r: 18, name: 'Qwen2.5 Coder 32B Instruct', org: 'Qwen', score: 38.0 },
        { r: 19, name: 'Qwen2.5 (7B + 72B)', org: 'Qwen', score: 32.8 }
      ],
      us: [
        { r: 1, name: 'Claude 4.5 Opus', org: 'Anthropic', score: 79.2 },
        { r: 2, name: 'Gemini 3 Pro Preview', org: 'Google DeepMind', score: 77.4 },
        { r: 3, name: 'Claude 4 Sonnet', org: 'Anthropic', score: 76.8 },
        { r: 4, name: 'Gemini 3 Flash', org: 'Google DeepMind', score: 75.8 },
        { r: 5, name: 'Claude 4.6 Opus', org: 'Anthropic', score: 75.6 },
        { r: 6, name: 'Claude Sonnet 4', org: 'Anthropic', score: 74.8 },
        { r: 7, name: 'Claude 4.5 Sonnet', org: 'Anthropic', score: 74.8 },
        { r: 8, name: 'GPT 5', org: 'OpenAI', score: 74.4 },
        { r: 9, name: 'Claude 4 Opus', org: 'Anthropic', score: 73.2 },
        { r: 10, name: 'GPT 5.2', org: 'OpenAI', score: 72.8 },
        { r: 11, name: 'GPT 5.2 Codex', org: 'OpenAI', score: 72.8 },
        { r: 12, name: 'Gemini 3 Pro', org: 'Google DeepMind', score: 69.6 },
        { r: 13, name: 'Claude 4.5 Haiku', org: 'Anthropic', score: 66.6 },
        { r: 14, name: 'Claude 3.7 Sonnet', org: 'Anthropic', score: 66.4 },
        { r: 15, name: 'GPT 5.1', org: 'OpenAI', score: 66.0 },
        { r: 16, name: 'GPT 5.1 Codex', org: 'OpenAI', score: 66.0 },
        { r: 17, name: 'o1 Preview', org: 'OpenAI', score: 64.6 },
        { r: 18, name: 'o4 Mini', org: 'OpenAI', score: 64.6 },
        { r: 19, name: 'Claude 3.5 Sonnet', org: 'Anthropic', score: 63.4 },
        { r: 20, name: 'Claude 3.7 Sonnet W/ Review Heavy', org: 'Anthropic', score: 62.4 }
      ]
    }
  }
];

window.TAGS = {
  assistant: { zh: '文本对话', en: 'Chat & Text' },
  agent:     { zh: 'Agent 智能体', en: 'Agent' },
  search:    { zh: 'AI 搜索',  en: 'Search' },
  image:     { zh: '图像生成', en: 'Image' },
  video:     { zh: '视频生成', en: 'Video' },
  audio:     { zh: '语音',     en: 'Audio' },
  portal:    { zh: '平台社区', en: 'Platform' },
  lab:       { zh: '前沿实验室', en: 'Lab' },
  coding:    { zh: 'AI 编程',  en: 'Coding' },
  productivity: { zh: '办公效率', en: 'Productivity' },
  media:     { zh: '资讯媒体', en: 'Media' },
  model:     { zh: '开源模型', en: 'Model' },
  app:       { zh: '应用框架', en: 'App & Framework' },
  infra:     { zh: '推理与工具链', en: 'Inference & Infra' },
  vision:    { zh: '视觉',     en: 'Vision' },
  'skill-tool':    { zh: '效率工具', en: 'Utility' },
  'skill-dev':     { zh: '开发编程', en: 'Dev & Code' },
  'skill-plan':    { zh: '规划设计', en: 'Plan & Design' },
  'skill-content': { zh: '内容创作', en: 'Content' },
  'skill-doc':     { zh: '文档办公', en: 'Documents' },
  'skill-learn':   { zh: '学习成长', en: 'Learning' },
  'skill-market':  { zh: '营销增长', en: 'Marketing' },
};
